// <auto-generated />
using System;
using FahrzeugZulassung.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FahrzeugZulassung.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AlteWerte")
                        .HasColumnType("text");

                    b.Property<Guid?>("BenutzerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Entitaet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntitaetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IPAdresse")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NeueWerte")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Aktion");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("Entitaet");

                    b.HasIndex("EntitaetId");

                    b.HasIndex("Zeitstempel");

                    b.HasIndex("Entitaet", "EntitaetId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Auftrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AGBAkzeptiert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("AGBAkzeptiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AbgeschlossenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AnIKfzGesendetAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuftragNummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Bemerkungen")
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ErstelltVonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FahrzeugId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IKfzAntwort")
                        .HasColumnType("text");

                    b.Property<string>("IKfzReferenz")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KundeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StandortId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Entwurf");

                    b.Property<bool>("Step1Abgeschlossen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Step2Abgeschlossen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Step3Abgeschlossen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UnterschriftAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UnterschriftVorhanden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AuftragNummer")
                        .IsUnique();

                    b.HasIndex("ErstelltAm");

                    b.HasIndex("ErstelltVonId");

                    b.HasIndex("FahrzeugId");

                    b.HasIndex("IKfzReferenz");

                    b.HasIndex("KundeId");

                    b.HasIndex("StandortId");

                    b.HasIndex("Status");

                    b.ToTable("Auftraege");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Benutzer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FehlgeschlageneLoginVersuche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GesperrtBis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("StandortId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StandortId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Dokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuftragId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("DateiGroesse")
                        .HasColumnType("bigint");

                    b.Property<string>("DateiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DateiPfad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HochgeladenVonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuftragId");

                    b.HasIndex("HochgeladenAm");

                    b.HasIndex("HochgeladenVonId");

                    b.HasIndex("Typ");

                    b.ToTable("Dokumente");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Fahrzeug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Erstzulassung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Farbe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Hubraum")
                        .HasColumnType("integer");

                    b.Property<string>("Kennzeichen")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Kraftstoffart")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Leistung")
                        .HasColumnType("integer");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FIN")
                        .IsUnique();

                    b.HasIndex("Kennzeichen");

                    b.HasIndex("Marke", "Modell");

                    b.ToTable("Fahrzeuge");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Kunde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BenutzerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DatenschutzAkzeptiert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DatenschutzAkzeptiertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Geburtsdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("Nachname", "Vorname");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Rechnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuftragId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("BezahltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Faellig")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RechnungNummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Offen");

                    b.Property<string>("ZahlungsReferenz")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Zahlungsmethode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuftragId");

                    b.HasIndex("BezahltAm");

                    b.HasIndex("Faellig");

                    b.HasIndex("RechnungNummer")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Rechnungen");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Standort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IstAktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IstAktiv");

                    b.HasIndex("Name");

                    b.HasIndex("PLZ");

                    b.ToTable("Standorte");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", "Benutzer")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Auftrag", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", "ErstelltVon")
                        .WithMany("ErstellteAuftraege")
                        .HasForeignKey("ErstelltVonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FahrzeugZulassung.Domain.Entities.Fahrzeug", "Fahrzeug")
                        .WithMany("Auftraege")
                        .HasForeignKey("FahrzeugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FahrzeugZulassung.Domain.Entities.Kunde", "Kunde")
                        .WithMany("Auftraege")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FahrzeugZulassung.Domain.Entities.Standort", "Standort")
                        .WithMany("Auftraege")
                        .HasForeignKey("StandortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErstelltVon");

                    b.Navigation("Fahrzeug");

                    b.Navigation("Kunde");

                    b.Navigation("Standort");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Benutzer", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Standort", "Standort")
                        .WithMany("Mitarbeiter")
                        .HasForeignKey("StandortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Standort");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Dokument", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Auftrag", "Auftrag")
                        .WithMany("Dokumente")
                        .HasForeignKey("AuftragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", "HochgeladenVon")
                        .WithMany()
                        .HasForeignKey("HochgeladenVonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auftrag");

                    b.Navigation("HochgeladenVon");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Kunde", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", "Benutzer")
                        .WithOne()
                        .HasForeignKey("FahrzeugZulassung.Domain.Entities.Kunde", "BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Rechnung", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Auftrag", "Auftrag")
                        .WithMany("Rechnungen")
                        .HasForeignKey("AuftragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auftrag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FahrzeugZulassung.Domain.Entities.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Auftrag", b =>
                {
                    b.Navigation("Dokumente");

                    b.Navigation("Rechnungen");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Benutzer", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ErstellteAuftraege");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Fahrzeug", b =>
                {
                    b.Navigation("Auftraege");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Kunde", b =>
                {
                    b.Navigation("Auftraege");
                });

            modelBuilder.Entity("FahrzeugZulassung.Domain.Entities.Standort", b =>
                {
                    b.Navigation("Auftraege");

                    b.Navigation("Mitarbeiter");
                });
#pragma warning restore 612, 618
        }
    }
}
