<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FahrzeugZulassung.Domain\FahrzeugZulassung.Domain.csproj" />
    <ProjectReference Include="..\FahrzeugZulassung.Infrastructure\FahrzeugZulassung.Infrastructure.csproj" />
  </ItemGroup>

</Project>
